INSERT INTO STUDENT_MEMBERS VALUES 
(76, " ","K. Navya Sree"," ",'F',"navyakadiyala1234@gmail.com"," "),
(77, " ","Ch.Jwalitha"," ",'F',"jwalitha.challagulla@gmail.com"," "),
(78, " ","A. Leela Krishna"," ",'M',"leelakrishnaalahari@gmail.com"," "),
(79, " ","K. Sree Deepthi"," ",'F',"kakumanisreedeepthi@gmail.com"," "),
(81, " ","A. Gideon Paul"," ",'M',"gidzpaul95@gmail.com"," "),
(82, " ","M.N.V.Satya Narayana"," ",'M',"satyam.codex@gmail.com"," "),
(83, " ","Sameera Sepuri"," ",'F',"Sameera.sepuri@gmail.com"," "),
(84, " ","V.Naga Sowjanya"," ",'F',"vellaturisowjanya@gmail.com"," "),
(85, " ","K Ajay Krishna Teja"," ",'M',"ajaykrishnateja@gmail.com"," "),
(86, " ","N.Kausalya"," ",'F',"nallurikausalya@gmail.com"," "),
(87, " ","Prakash Jada"," ",'M',"prakash.j.476@gmail.com"," "),
(88, " ","G.Sai Chandra Srivatsav"," ",'M',"saichandrasrivatsav@ymail.com"," "),
(89, " ","M.Sathvik"," ",'M',"sathvik.2010@gmail.com"," "),
(90, " ","D.Vasanthi"," ",'F',"vasanthidodda@gmail.com"," "),
(91, " ","M.Sriram kumar"," ",'M',"sriramkumar563@gmail.com"," "),
(92, " ","A.Satya Kalyan"," ",'M',"Satyakalyan_a@yahoo.com"," "),
(93, " ","A.sudhir Babu"," ",'M',"asbabu@hotmail.com"," "),
(94, " ","D.SrikarReddy"," ",'M',"Srikar.4246@gmail.com"," "),
(96, " ","S V R S N Shashank"," ",'M',"Shashank16392@gmail.com"," "),
(97, " ","V.Asha"," ",'F',"Anu80koneru@gmail.com"," "),
(98, " ","T.Chakravarthi"," ",'M',"t.chakravarthi9@gmail.com"," "),
(99, " ","Nurunissa Shaik"," ",'F',"shaiknoor571@gmail.com"," "),
(100, " ","M.Praneeth"," ",'M',"praneeth.mareedu@gmail.com"," "),
(101, " ","Sandhya Kancharla"," ",'F',"winne.sannidi@gmail.com"," "),
(102, " ","M.V.V.N.S Narayana"," ",'M',"satya_muttha@yahoo.com"," "),
(103, " ","M.Siva Naga Raju"," ",'M',"nagasiva512@gmail.com"," "),
(104, " ","Ch.V.S.Suryanarayana"," ",'M',"chundurisurya@yahoo.com"," "),
(105, " ","B.Vijayasri"," ",'F',"vijaya.b81@gmail.com"," "),
(106, " ","K.Bala Karthikeya"," ",'M',"kbk.sri@gmail.com"," "),
(107, " ","L.Avinash"," ",'',"lingabathiniavinash@gmail.com"," "),
(108, " ","K.V Nagarajuna Krishna"," ",'M',"krishna6066@gmail.com"," "),
(109, " ","Z.Pavan Kumar"," ",'M',"pkzpavan_007@yahoo.com"," "),
(110, " ","T.Ramya"," ",'F',"ramyacse8@gmail.com"," "),
(111, " ","T.Yamini"," ",'F',"yaminitondepu@yahoo.co.in"," "),
(112, " ","Roopa Venna"," ",'F',"rupa_honey2001@yahoo.co.in"," "),
(113, " ","Ramya Marella"," ",'F',"ramyamarella554@gmail.com"," "),
(114, " ","Rajesh Pedamutti"," ",'M',"rajeshpedamutti@yahoo.com"," "),
(115, " ","Mukkamula Avinash"," ",'M',"avinashmukkamula@yahoo.com"," "),
(116, " ","P.Krishna Prasanna"," ",'F',"krishna_cse55@yahoo.com"," "),
(117, " ","T.V.Krishna Chowdary"," ",'M',"tkrishna09@gmail.com"," "),
(118, " ","Kodeti Shalini"," ",'F',"shalinikondeti6@gmail.com"," "),
(119, " ","B.Venkateshwara Rao"," ",'M',"bvenkat70@gmail.com"," "),
(120, " ","A.Bhaskara Srinivas"," ",'M',"srinivasampolu@gmail.com"," "),
(121, " ","D.Krishna"," ",'M',"Krishna.davuluri@gmail.com"," ");
