INSERT INTO STUDENT_MEMBERS VALUES 
(76, " ","K. Navya Sree",0,'F',"navyakadiyala1234@gmail.com"," "),
(77, " ","Ch.Jwalitha",0,'F',"jwalitha.challagulla@gmail.com"," "),
(78, " ","A. Leela Krishna",0,'M',"leelakrishnaalahari@gmail.com"," "),
(79, " ","K. Sree Deepthi",0,'F',"kakumanisreedeepthi@gmail.com"," "),
(81, " ","A. Gideon Paul",0,'M',"gidzpaul95@gmail.com"," "),
(82, " ","M.N.V.Satya Narayana",0,'M',"satyam.codex@gmail.com"," "),
(83, " ","Sameera Sepuri",0,'F',"Sameera.sepuri@gmail.com"," "),
(84, " ","V.Naga Sowjanya",0,'F',"vellaturisowjanya@gmail.com"," "),
(85, " ","K Ajay Krishna Teja",0,'M',"ajaykrishnateja@gmail.com"," "),
(86, " ","N.Kausalya",0,'F',"nallurikausalya@gmail.com"," "),
(87, " ","Prakash Jada",0,'M',"prakash.j.476@gmail.com"," "),
(88, " ","G.Sai Chandra Srivatsav",0,'M',"saichandrasrivatsav@ymail.com"," "),
(89, " ","M.Sathvik",0,'M',"sathvik.2010@gmail.com"," "),
(90, " ","D.Vasanthi",0,'F',"vasanthidodda@gmail.com"," "),
(91, " ","M.Sriram kumar",0,'M',"sriramkumar563@gmail.com"," "),
(92, " ","A.Satya Kalyan",0,'M',"Satyakalyan_a@yahoo.com"," "),
(93, " ","A.sudhir Babu",0,'M',"asbabu@hotmail.com"," "),
(94, " ","D.SrikarReddy",0,'M',"Srikar.4246@gmail.com"," "),
(96, " ","S V R S N Shashank",0,'M',"Shashank16392@gmail.com"," "),
(97, " ","V.Asha",0,'F',"Anu80koneru@gmail.com"," "),
(98, " ","T.Chakravarthi",0,'M',"t.chakravarthi9@gmail.com"," "),
(99, " ","Nurunissa Shaik",0,'F',"shaiknoor571@gmail.com"," "),
(100, " ","M.Praneeth",0,'M',"praneeth.mareedu@gmail.com"," "),
(101, " ","Sandhya Kancharla",0,'F',"winne.sannidi@gmail.com"," "),
(102, " ","M.V.V.N.S Narayana",0,'M',"satya_muttha@yahoo.com"," "),
(103, " ","M.Siva Naga Raju",0,'M',"nagasiva512@gmail.com"," "),
(104, " ","Ch.V.S.Suryanarayana",0,'M',"chundurisurya@yahoo.com"," "),
(105, " ","B.Vijayasri",0,'F',"vijaya.b81@gmail.com"," "),
(106, " ","K.Bala Karthikeya",0,'M',"kbk.sri@gmail.com"," "),
(107, " ","L.Avinash",0,'M',"lingabathiniavinash@gmail.com"," "),
(108, " ","K.V Nagarajuna Krishna",0,'M',"krishna6066@gmail.com"," "),
(109, " ","Z.Pavan Kumar",0,'M',"pkzpavan_007@yahoo.com"," "),
(110, " ","T.Ramya",0,'F',"ramyacse8@gmail.com"," "),
(111, " ","T.Yamini",0,'F',"yaminitondepu@yahoo.co.in"," "),
(112, " ","Roopa Venna",0,'F',"rupa_honey2001@yahoo.co.in"," "),
(113, " ","Ramya Marella",0,'F',"ramyamarella554@gmail.com"," "),
(114, " ","Rajesh Pedamutti",0,'M',"rajeshpedamutti@yahoo.com"," "),
(115, " ","Mukkamula Avinash",0,'M',"avinashmukkamula@yahoo.com"," "),
(116, " ","P.Krishna Prasanna",0,'F',"krishna_cse55@yahoo.com"," "),
(117, " ","T.V.Krishna Chowdary",0,'M',"tkrishna09@gmail.com"," "),
(118, " ","Kodeti Shalini",0,'F',"shalinikondeti6@gmail.com"," "),
(119, " ","B.Venkateshwara Rao",0,'M',"bvenkat70@gmail.com"," "),
(120, " ","A.Bhaskara Srinivas",0,'M',"srinivasampolu@gmail.com"," "),
(121, " ","D.Krishna",0,'M',"Krishna.davuluri@gmail.com"," ");
